spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpaex?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kris2486!

    #    url: jdbc:mysql://ccr.cl8zlarfimpv.ap-jnortheast-2.rds.amazonaws.com:3306/ccr?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username:
    #    password:

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

    database: mysql

  mvc:
    path match:
      matching-strategy: ant_path_matcher


logging:
  level:
    org.hibernate.SQL: debug
